require: rubocop-rails

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.6
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: true
Rails/WhereNot: # new in 2.8
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Style/GuardClause:
  Enabled: false
