volumes:
  postgres:
  solr:

networks:
  internal:

x-app: &app
  env_file:
    - .env
  environment:
    no_proxy: localhost,web,queue,tika
  build:
    context: .
    args:
      - UID=${UID}
      - GID=${GID}
      - http_proxy=${http_proxy}
      - https_proxy=${http_proxy}
  image: ghcr.io/next-l/enju_leaf:latest
  networks:
    internal:
  volumes:
    - ./:/enju
  depends_on:
    - solr
  restart: always

services:
  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -b 0.0.0.0"
    expose:
      - 3000

  queue:
    <<: *app
    command: bash -c "bin/jobs"

  solr:
    image: solr:8
    ports:
      - 8983:8983
    env_file:
      - .env
    networks:
      internal:
    volumes:
      - solr:/var/solr/data
      - ./solr:/mnt/solr
    restart: always
    command: bash -c "precreate-core enju_leaf_${RAILS_ENV} /mnt/solr/configsets/sunspot/conf/; precreate-core enju_leaf_test /mnt/solr/configsets/sunspot/conf/; exec solr -f"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8983/solr/enju_leaf_${RAILS_ENV}/admin/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  cantaloupe:
    image: islandora/cantaloupe:5.1
    expose:
      - 8182
    restart: always
    environment:
      - CANTALOUPE_HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_PREFIX=http://web:3000/picture_files/
      - CANTALOUPE_HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_SUFFIX=/download
      - CANTALOUPE_ENDPOINT_API_ENABLED=true
    networks:
      internal:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://cantaloupe:8182/health"]
      interval: 30s
      timeout: 20s
      retries: 3

  tika:
    image: apache/tika:3.2.3.0
    expose:
      - 9998
    restart: always
    networks:
      internal:
