require 'csv' if RUBY_VERSION > '1.9'
#require 'mathn'
require 'rss'
require 'nkf'
require 'ipaddr'
require 'plugins'
require 'will_paginate/array'
require 'enju_leaf/bookmark_url'
require 'enju_leaf/calculate_stat'
require 'enju_leaf/openurl'
require 'enju_leaf/porta_cql'
require 'enju_leaf/sru'
require 'enju_leaf/version'
