#!/usr/bin/env ruby
require 'fileutils'

case ARGV[0]
when 'pgsql'
  adapter = 'pgsql'
when 'mysql'
  adapter = 'mysql'
when 'sqlite'
  adapter = 'sqlite'
else
  raise 'please choose one from pgsql, mysql and sqlite.'
end

unless File.exists?("config/database.yml")
  FileUtils.cp "config/database.yml.sample-#{adapter}", "config/database.yml"
  puts "copied config/database.yml"
end

unless File.exists?("config/application.rb")
  FileUtils.cp "config/application.rb.sample", "config/application.rb"
  puts "copied config/application.rb"
end
