#!/usr/bin/env ruby
require 'rubygems'
require 'fileutils'

case ARGV[0]
when 'pgsql'
  adapter = 'pgsql'
when 'mysql'
  adapter = 'mysql'
when 'sqlite'
  adapter = 'sqlite'
else
  raise 'please choose one from pgsql, mysql and sqlite.'
end

unless File.exists?("config/database.yml")
  FileUtils.cp "config/database.yml.sample-#{adapter}", "config/database.yml"
  puts "copied config/database.yml"
end

sample_files = [
  "config/initializers/devise.rb.sample",
  "config/initializers/secret_token.rb.sample",
  "config/configatron/production.rb.sample",
  "config/environments/production.rb.sample",
  "config/schedule.rb.sample",
  "config/sunspot.yml.sample",
  "db/seeds.rb.sample"
]
  
sample_files.each do |file|
  dist = file.gsub(/\.sample$/, '')
  unless File.exists?(dist)
    FileUtils.cp file, dist
    puts "copied #{file}"
  end
end
