require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcceptsController do

  # This should return the minimal set of attributes required to create a valid
  # Accept. As you add validations to Accept, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcceptsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all accepts as @accepts" do
      accept = Accept.create! valid_attributes
      get :index, {}, valid_session
      assigns(:accepts).should eq([accept])
    end
  end

  describe "GET show" do
    it "assigns the requested accept as @accept" do
      accept = Accept.create! valid_attributes
      get :show, {:id => accept.to_param}, valid_session
      assigns(:accept).should eq(accept)
    end
  end

  describe "GET new" do
    it "assigns a new accept as @accept" do
      get :new, {}, valid_session
      assigns(:accept).should be_a_new(Accept)
    end
  end

  describe "GET edit" do
    it "assigns the requested accept as @accept" do
      accept = Accept.create! valid_attributes
      get :edit, {:id => accept.to_param}, valid_session
      assigns(:accept).should eq(accept)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Accept" do
        expect {
          post :create, {:accept => valid_attributes}, valid_session
        }.to change(Accept, :count).by(1)
      end

      it "assigns a newly created accept as @accept" do
        post :create, {:accept => valid_attributes}, valid_session
        assigns(:accept).should be_a(Accept)
        assigns(:accept).should be_persisted
      end

      it "redirects to the created accept" do
        post :create, {:accept => valid_attributes}, valid_session
        response.should redirect_to(Accept.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accept as @accept" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accept.any_instance.stub(:save).and_return(false)
        post :create, {:accept => {}}, valid_session
        assigns(:accept).should be_a_new(Accept)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accept.any_instance.stub(:save).and_return(false)
        post :create, {:accept => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accept" do
        accept = Accept.create! valid_attributes
        # Assuming there are no other accepts in the database, this
        # specifies that the Accept created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Accept.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => accept.to_param, :accept => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested accept as @accept" do
        accept = Accept.create! valid_attributes
        put :update, {:id => accept.to_param, :accept => valid_attributes}, valid_session
        assigns(:accept).should eq(accept)
      end

      it "redirects to the accept" do
        accept = Accept.create! valid_attributes
        put :update, {:id => accept.to_param, :accept => valid_attributes}, valid_session
        response.should redirect_to(accept)
      end
    end

    describe "with invalid params" do
      it "assigns the accept as @accept" do
        accept = Accept.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accept.any_instance.stub(:save).and_return(false)
        put :update, {:id => accept.to_param, :accept => {}}, valid_session
        assigns(:accept).should eq(accept)
      end

      it "re-renders the 'edit' template" do
        accept = Accept.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accept.any_instance.stub(:save).and_return(false)
        put :update, {:id => accept.to_param, :accept => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accept" do
      accept = Accept.create! valid_attributes
      expect {
        delete :destroy, {:id => accept.to_param}, valid_session
      }.to change(Accept, :count).by(-1)
    end

    it "redirects to the accepts list" do
      accept = Accept.create! valid_attributes
      delete :destroy, {:id => accept.to_param}, valid_session
      response.should redirect_to(accepts_url)
    end
  end

end
