require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnjuTerminalsController do

  # This should return the minimal set of attributes required to create a valid
  # EnjuTerminal. As you add validations to EnjuTerminal, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "ipaddr" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnjuTerminalsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all enju_terminals as @enju_terminals" do
      enju_terminal = EnjuTerminal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:enju_terminals).should eq([enju_terminal])
    end
  end

  describe "GET show" do
    it "assigns the requested enju_terminal as @enju_terminal" do
      enju_terminal = EnjuTerminal.create! valid_attributes
      get :show, {:id => enju_terminal.to_param}, valid_session
      assigns(:enju_terminal).should eq(enju_terminal)
    end
  end

  describe "GET new" do
    it "assigns a new enju_terminal as @enju_terminal" do
      get :new, {}, valid_session
      assigns(:enju_terminal).should be_a_new(EnjuTerminal)
    end
  end

  describe "GET edit" do
    it "assigns the requested enju_terminal as @enju_terminal" do
      enju_terminal = EnjuTerminal.create! valid_attributes
      get :edit, {:id => enju_terminal.to_param}, valid_session
      assigns(:enju_terminal).should eq(enju_terminal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EnjuTerminal" do
        expect {
          post :create, {:enju_terminal => valid_attributes}, valid_session
        }.to change(EnjuTerminal, :count).by(1)
      end

      it "assigns a newly created enju_terminal as @enju_terminal" do
        post :create, {:enju_terminal => valid_attributes}, valid_session
        assigns(:enju_terminal).should be_a(EnjuTerminal)
        assigns(:enju_terminal).should be_persisted
      end

      it "redirects to the created enju_terminal" do
        post :create, {:enju_terminal => valid_attributes}, valid_session
        response.should redirect_to(EnjuTerminal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enju_terminal as @enju_terminal" do
        # Trigger the behavior that occurs when invalid params are submitted
        EnjuTerminal.any_instance.stub(:save).and_return(false)
        post :create, {:enju_terminal => { "ipaddr" => "invalid value" }}, valid_session
        assigns(:enju_terminal).should be_a_new(EnjuTerminal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EnjuTerminal.any_instance.stub(:save).and_return(false)
        post :create, {:enju_terminal => { "ipaddr" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enju_terminal" do
        enju_terminal = EnjuTerminal.create! valid_attributes
        # Assuming there are no other enju_terminals in the database, this
        # specifies that the EnjuTerminal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EnjuTerminal.any_instance.should_receive(:update_attributes).with({ "ipaddr" => "MyString" })
        put :update, {:id => enju_terminal.to_param, :enju_terminal => { "ipaddr" => "MyString" }}, valid_session
      end

      it "assigns the requested enju_terminal as @enju_terminal" do
        enju_terminal = EnjuTerminal.create! valid_attributes
        put :update, {:id => enju_terminal.to_param, :enju_terminal => valid_attributes}, valid_session
        assigns(:enju_terminal).should eq(enju_terminal)
      end

      it "redirects to the enju_terminal" do
        enju_terminal = EnjuTerminal.create! valid_attributes
        put :update, {:id => enju_terminal.to_param, :enju_terminal => valid_attributes}, valid_session
        response.should redirect_to(enju_terminal)
      end
    end

    describe "with invalid params" do
      it "assigns the enju_terminal as @enju_terminal" do
        enju_terminal = EnjuTerminal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EnjuTerminal.any_instance.stub(:save).and_return(false)
        put :update, {:id => enju_terminal.to_param, :enju_terminal => { "ipaddr" => "invalid value" }}, valid_session
        assigns(:enju_terminal).should eq(enju_terminal)
      end

      it "re-renders the 'edit' template" do
        enju_terminal = EnjuTerminal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EnjuTerminal.any_instance.stub(:save).and_return(false)
        put :update, {:id => enju_terminal.to_param, :enju_terminal => { "ipaddr" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enju_terminal" do
      enju_terminal = EnjuTerminal.create! valid_attributes
      expect {
        delete :destroy, {:id => enju_terminal.to_param}, valid_session
      }.to change(EnjuTerminal, :count).by(-1)
    end

    it "redirects to the enju_terminals list" do
      enju_terminal = EnjuTerminal.create! valid_attributes
      delete :destroy, {:id => enju_terminal.to_param}, valid_session
      response.should redirect_to(enju_terminals_url)
    end
  end

end
