require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KeywordCountsController do

  # This should return the minimal set of attributes required to create a valid
  # KeywordCount. As you add validations to KeywordCount, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KeywordCountsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all keyword_counts as @keyword_counts" do
      keyword_count = KeywordCount.create! valid_attributes
      get :index, {}, valid_session
      assigns(:keyword_counts).should eq([keyword_count])
    end
  end

  describe "GET show" do
    it "assigns the requested keyword_count as @keyword_count" do
      keyword_count = KeywordCount.create! valid_attributes
      get :show, {:id => keyword_count.to_param}, valid_session
      assigns(:keyword_count).should eq(keyword_count)
    end
  end

  describe "GET new" do
    it "assigns a new keyword_count as @keyword_count" do
      get :new, {}, valid_session
      assigns(:keyword_count).should be_a_new(KeywordCount)
    end
  end

  describe "GET edit" do
    it "assigns the requested keyword_count as @keyword_count" do
      keyword_count = KeywordCount.create! valid_attributes
      get :edit, {:id => keyword_count.to_param}, valid_session
      assigns(:keyword_count).should eq(keyword_count)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KeywordCount" do
        expect {
          post :create, {:keyword_count => valid_attributes}, valid_session
        }.to change(KeywordCount, :count).by(1)
      end

      it "assigns a newly created keyword_count as @keyword_count" do
        post :create, {:keyword_count => valid_attributes}, valid_session
        assigns(:keyword_count).should be_a(KeywordCount)
        assigns(:keyword_count).should be_persisted
      end

      it "redirects to the created keyword_count" do
        post :create, {:keyword_count => valid_attributes}, valid_session
        response.should redirect_to(KeywordCount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved keyword_count as @keyword_count" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeywordCount.any_instance.stub(:save).and_return(false)
        post :create, {:keyword_count => {}}, valid_session
        assigns(:keyword_count).should be_a_new(KeywordCount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeywordCount.any_instance.stub(:save).and_return(false)
        post :create, {:keyword_count => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested keyword_count" do
        keyword_count = KeywordCount.create! valid_attributes
        # Assuming there are no other keyword_counts in the database, this
        # specifies that the KeywordCount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KeywordCount.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => keyword_count.to_param, :keyword_count => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested keyword_count as @keyword_count" do
        keyword_count = KeywordCount.create! valid_attributes
        put :update, {:id => keyword_count.to_param, :keyword_count => valid_attributes}, valid_session
        assigns(:keyword_count).should eq(keyword_count)
      end

      it "redirects to the keyword_count" do
        keyword_count = KeywordCount.create! valid_attributes
        put :update, {:id => keyword_count.to_param, :keyword_count => valid_attributes}, valid_session
        response.should redirect_to(keyword_count)
      end
    end

    describe "with invalid params" do
      it "assigns the keyword_count as @keyword_count" do
        keyword_count = KeywordCount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeywordCount.any_instance.stub(:save).and_return(false)
        put :update, {:id => keyword_count.to_param, :keyword_count => {}}, valid_session
        assigns(:keyword_count).should eq(keyword_count)
      end

      it "re-renders the 'edit' template" do
        keyword_count = KeywordCount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeywordCount.any_instance.stub(:save).and_return(false)
        put :update, {:id => keyword_count.to_param, :keyword_count => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested keyword_count" do
      keyword_count = KeywordCount.create! valid_attributes
      expect {
        delete :destroy, {:id => keyword_count.to_param}, valid_session
      }.to change(KeywordCount, :count).by(-1)
    end

    it "redirects to the keyword_counts list" do
      keyword_count = KeywordCount.create! valid_attributes
      delete :destroy, {:id => keyword_count.to_param}, valid_session
      response.should redirect_to(keyword_counts_url)
    end
  end

end
