require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NumberingsController do

  # This should return the minimal set of attributes required to create a valid
  # Numbering. As you add validations to Numbering, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NumberingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all numberings as @numberings" do
      numbering = Numbering.create! valid_attributes
      get :index, {}, valid_session
      assigns(:numberings).should eq([numbering])
    end
  end

  describe "GET show" do
    it "assigns the requested numbering as @numbering" do
      numbering = Numbering.create! valid_attributes
      get :show, {:id => numbering.to_param}, valid_session
      assigns(:numbering).should eq(numbering)
    end
  end

  describe "GET new" do
    it "assigns a new numbering as @numbering" do
      get :new, {}, valid_session
      assigns(:numbering).should be_a_new(Numbering)
    end
  end

  describe "GET edit" do
    it "assigns the requested numbering as @numbering" do
      numbering = Numbering.create! valid_attributes
      get :edit, {:id => numbering.to_param}, valid_session
      assigns(:numbering).should eq(numbering)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Numbering" do
        expect {
          post :create, {:numbering => valid_attributes}, valid_session
        }.to change(Numbering, :count).by(1)
      end

      it "assigns a newly created numbering as @numbering" do
        post :create, {:numbering => valid_attributes}, valid_session
        assigns(:numbering).should be_a(Numbering)
        assigns(:numbering).should be_persisted
      end

      it "redirects to the created numbering" do
        post :create, {:numbering => valid_attributes}, valid_session
        response.should redirect_to(Numbering.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved numbering as @numbering" do
        # Trigger the behavior that occurs when invalid params are submitted
        Numbering.any_instance.stub(:save).and_return(false)
        post :create, {:numbering => { "name" => "invalid value" }}, valid_session
        assigns(:numbering).should be_a_new(Numbering)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Numbering.any_instance.stub(:save).and_return(false)
        post :create, {:numbering => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested numbering" do
        numbering = Numbering.create! valid_attributes
        # Assuming there are no other numberings in the database, this
        # specifies that the Numbering created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Numbering.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => numbering.to_param, :numbering => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested numbering as @numbering" do
        numbering = Numbering.create! valid_attributes
        put :update, {:id => numbering.to_param, :numbering => valid_attributes}, valid_session
        assigns(:numbering).should eq(numbering)
      end

      it "redirects to the numbering" do
        numbering = Numbering.create! valid_attributes
        put :update, {:id => numbering.to_param, :numbering => valid_attributes}, valid_session
        response.should redirect_to(numbering)
      end
    end

    describe "with invalid params" do
      it "assigns the numbering as @numbering" do
        numbering = Numbering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Numbering.any_instance.stub(:save).and_return(false)
        put :update, {:id => numbering.to_param, :numbering => { "name" => "invalid value" }}, valid_session
        assigns(:numbering).should eq(numbering)
      end

      it "re-renders the 'edit' template" do
        numbering = Numbering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Numbering.any_instance.stub(:save).and_return(false)
        put :update, {:id => numbering.to_param, :numbering => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested numbering" do
      numbering = Numbering.create! valid_attributes
      expect {
        delete :destroy, {:id => numbering.to_param}, valid_session
      }.to change(Numbering, :count).by(-1)
    end

    it "redirects to the numberings list" do
      numbering = Numbering.create! valid_attributes
      delete :destroy, {:id => numbering.to_param}, valid_session
      response.should redirect_to(numberings_url)
    end
  end

end
