require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProduceTypesController do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # ProduceType. As you add validations to ProduceType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:produce_type)
  end

  describe "GET index" do
    it "assigns all produce_types as @produce_types" do
      produce_type = ProduceType.create! valid_attributes
      get :index
      assigns(:produce_types).should eq(ProduceType.all)
    end
  end

  describe "GET show" do
    it "assigns the requested produce_type as @produce_type" do
      produce_type = ProduceType.create! valid_attributes
      get :show, :id => produce_type.id
      assigns(:produce_type).should eq(produce_type)
    end
  end

  describe "GET new" do
    it "assigns a new produce_type as @produce_type" do
      get :new
      assigns(:produce_type).should be_a_new(ProduceType)
    end
  end

  describe "GET edit" do
    it "assigns the requested produce_type as @produce_type" do
      produce_type = ProduceType.create! valid_attributes
      get :edit, :id => produce_type.id
      assigns(:produce_type).should eq(produce_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProduceType" do
        expect {
          post :create, :produce_type => valid_attributes
        }.to change(ProduceType, :count).by(1)
      end

      it "assigns a newly created produce_type as @produce_type" do
        post :create, :produce_type => valid_attributes
        assigns(:produce_type).should be_a(ProduceType)
        assigns(:produce_type).should be_persisted
      end

      it "redirects to the created produce_type" do
        post :create, :produce_type => valid_attributes
        response.should redirect_to(ProduceType.first)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved produce_type as @produce_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProduceType.any_instance.stub(:save).and_return(false)
        post :create, :produce_type => {}
        assigns(:produce_type).should be_a_new(ProduceType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProduceType.any_instance.stub(:save).and_return(false)
        post :create, :produce_type => {}
        #response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested produce_type" do
        produce_type = ProduceType.create! valid_attributes
        # Assuming there are no other produce_types in the database, this
        # specifies that the ProduceType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProduceType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => produce_type.id, :produce_type => {'these' => 'params'}
      end

      it "assigns the requested produce_type as @produce_type" do
        produce_type = ProduceType.create! valid_attributes
        put :update, :id => produce_type.id, :produce_type => valid_attributes
        assigns(:produce_type).should eq(produce_type)
      end

      it "redirects to the produce_type" do
        produce_type = ProduceType.create! valid_attributes
        put :update, :id => produce_type.id, :produce_type => valid_attributes
        response.should redirect_to(produce_type)
      end
    end

    describe "with invalid params" do
      it "assigns the produce_type as @produce_type" do
        produce_type = ProduceType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProduceType.any_instance.stub(:save).and_return(false)
        put :update, :id => produce_type.id, :produce_type => {}
        assigns(:produce_type).should eq(produce_type)
      end

      it "re-renders the 'edit' template" do
        produce_type = ProduceType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProduceType.any_instance.stub(:save).and_return(false)
        put :update, :id => produce_type.id, :produce_type => {}
        #response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested produce_type" do
      produce_type = ProduceType.create! valid_attributes
      expect {
        delete :destroy, :id => produce_type.id
      }.to change(ProduceType, :count).by(-1)
    end

    it "redirects to the produce_types list" do
      produce_type = ProduceType.create! valid_attributes
      delete :destroy, :id => produce_type.id
      response.should redirect_to(produce_types_url)
    end
  end

end
