require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RelationshipFamiliesController do

  # This should return the minimal set of attributes required to create a valid
  # RelationshipFamily. As you add validations to RelationshipFamily, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "display_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RelationshipFamiliesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all relationship_families as @relationship_families" do
      relationship_family = RelationshipFamily.create! valid_attributes
      get :index, {}, valid_session
      assigns(:relationship_families).should eq([relationship_family])
    end
  end

  describe "GET show" do
    it "assigns the requested relationship_family as @relationship_family" do
      relationship_family = RelationshipFamily.create! valid_attributes
      get :show, {:id => relationship_family.to_param}, valid_session
      assigns(:relationship_family).should eq(relationship_family)
    end
  end

  describe "GET new" do
    it "assigns a new relationship_family as @relationship_family" do
      get :new, {}, valid_session
      assigns(:relationship_family).should be_a_new(RelationshipFamily)
    end
  end

  describe "GET edit" do
    it "assigns the requested relationship_family as @relationship_family" do
      relationship_family = RelationshipFamily.create! valid_attributes
      get :edit, {:id => relationship_family.to_param}, valid_session
      assigns(:relationship_family).should eq(relationship_family)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RelationshipFamily" do
        expect {
          post :create, {:relationship_family => valid_attributes}, valid_session
        }.to change(RelationshipFamily, :count).by(1)
      end

      it "assigns a newly created relationship_family as @relationship_family" do
        post :create, {:relationship_family => valid_attributes}, valid_session
        assigns(:relationship_family).should be_a(RelationshipFamily)
        assigns(:relationship_family).should be_persisted
      end

      it "redirects to the created relationship_family" do
        post :create, {:relationship_family => valid_attributes}, valid_session
        response.should redirect_to(RelationshipFamily.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved relationship_family as @relationship_family" do
        # Trigger the behavior that occurs when invalid params are submitted
        RelationshipFamily.any_instance.stub(:save).and_return(false)
        post :create, {:relationship_family => { "display_name" => "invalid value" }}, valid_session
        assigns(:relationship_family).should be_a_new(RelationshipFamily)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RelationshipFamily.any_instance.stub(:save).and_return(false)
        post :create, {:relationship_family => { "display_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested relationship_family" do
        relationship_family = RelationshipFamily.create! valid_attributes
        # Assuming there are no other relationship_families in the database, this
        # specifies that the RelationshipFamily created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RelationshipFamily.any_instance.should_receive(:update_attributes).with({ "display_name" => "MyString" })
        put :update, {:id => relationship_family.to_param, :relationship_family => { "display_name" => "MyString" }}, valid_session
      end

      it "assigns the requested relationship_family as @relationship_family" do
        relationship_family = RelationshipFamily.create! valid_attributes
        put :update, {:id => relationship_family.to_param, :relationship_family => valid_attributes}, valid_session
        assigns(:relationship_family).should eq(relationship_family)
      end

      it "redirects to the relationship_family" do
        relationship_family = RelationshipFamily.create! valid_attributes
        put :update, {:id => relationship_family.to_param, :relationship_family => valid_attributes}, valid_session
        response.should redirect_to(relationship_family)
      end
    end

    describe "with invalid params" do
      it "assigns the relationship_family as @relationship_family" do
        relationship_family = RelationshipFamily.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RelationshipFamily.any_instance.stub(:save).and_return(false)
        put :update, {:id => relationship_family.to_param, :relationship_family => { "display_name" => "invalid value" }}, valid_session
        assigns(:relationship_family).should eq(relationship_family)
      end

      it "re-renders the 'edit' template" do
        relationship_family = RelationshipFamily.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RelationshipFamily.any_instance.stub(:save).and_return(false)
        put :update, {:id => relationship_family.to_param, :relationship_family => { "display_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested relationship_family" do
      relationship_family = RelationshipFamily.create! valid_attributes
      expect {
        delete :destroy, {:id => relationship_family.to_param}, valid_session
      }.to change(RelationshipFamily, :count).by(-1)
    end

    it "redirects to the relationship_families list" do
      relationship_family = RelationshipFamily.create! valid_attributes
      delete :destroy, {:id => relationship_family.to_param}, valid_session
      response.should redirect_to(relationship_families_url)
    end
  end

end
