require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RemoveReasonsController do

  # This should return the minimal set of attributes required to create a valid
  # RemoveReason. As you add validations to RemoveReason, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RemoveReasonsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all remove_reasons as @remove_reasons" do
      remove_reason = RemoveReason.create! valid_attributes
      get :index, {}, valid_session
      assigns(:remove_reasons).should eq([remove_reason])
    end
  end

  describe "GET show" do
    it "assigns the requested remove_reason as @remove_reason" do
      remove_reason = RemoveReason.create! valid_attributes
      get :show, {:id => remove_reason.to_param}, valid_session
      assigns(:remove_reason).should eq(remove_reason)
    end
  end

  describe "GET new" do
    it "assigns a new remove_reason as @remove_reason" do
      get :new, {}, valid_session
      assigns(:remove_reason).should be_a_new(RemoveReason)
    end
  end

  describe "GET edit" do
    it "assigns the requested remove_reason as @remove_reason" do
      remove_reason = RemoveReason.create! valid_attributes
      get :edit, {:id => remove_reason.to_param}, valid_session
      assigns(:remove_reason).should eq(remove_reason)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RemoveReason" do
        expect {
          post :create, {:remove_reason => valid_attributes}, valid_session
        }.to change(RemoveReason, :count).by(1)
      end

      it "assigns a newly created remove_reason as @remove_reason" do
        post :create, {:remove_reason => valid_attributes}, valid_session
        assigns(:remove_reason).should be_a(RemoveReason)
        assigns(:remove_reason).should be_persisted
      end

      it "redirects to the created remove_reason" do
        post :create, {:remove_reason => valid_attributes}, valid_session
        response.should redirect_to(RemoveReason.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved remove_reason as @remove_reason" do
        # Trigger the behavior that occurs when invalid params are submitted
        RemoveReason.any_instance.stub(:save).and_return(false)
        post :create, {:remove_reason => {}}, valid_session
        assigns(:remove_reason).should be_a_new(RemoveReason)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RemoveReason.any_instance.stub(:save).and_return(false)
        post :create, {:remove_reason => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested remove_reason" do
        remove_reason = RemoveReason.create! valid_attributes
        # Assuming there are no other remove_reasons in the database, this
        # specifies that the RemoveReason created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RemoveReason.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => remove_reason.to_param, :remove_reason => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested remove_reason as @remove_reason" do
        remove_reason = RemoveReason.create! valid_attributes
        put :update, {:id => remove_reason.to_param, :remove_reason => valid_attributes}, valid_session
        assigns(:remove_reason).should eq(remove_reason)
      end

      it "redirects to the remove_reason" do
        remove_reason = RemoveReason.create! valid_attributes
        put :update, {:id => remove_reason.to_param, :remove_reason => valid_attributes}, valid_session
        response.should redirect_to(remove_reason)
      end
    end

    describe "with invalid params" do
      it "assigns the remove_reason as @remove_reason" do
        remove_reason = RemoveReason.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RemoveReason.any_instance.stub(:save).and_return(false)
        put :update, {:id => remove_reason.to_param, :remove_reason => {}}, valid_session
        assigns(:remove_reason).should eq(remove_reason)
      end

      it "re-renders the 'edit' template" do
        remove_reason = RemoveReason.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RemoveReason.any_instance.stub(:save).and_return(false)
        put :update, {:id => remove_reason.to_param, :remove_reason => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested remove_reason" do
      remove_reason = RemoveReason.create! valid_attributes
      expect {
        delete :destroy, {:id => remove_reason.to_param}, valid_session
      }.to change(RemoveReason, :count).by(-1)
    end

    it "redirects to the remove_reasons list" do
      remove_reason = RemoveReason.create! valid_attributes
      delete :destroy, {:id => remove_reason.to_param}, valid_session
      response.should redirect_to(remove_reasons_url)
    end
  end

end
