require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RetentionPeriodsController do

  # This should return the minimal set of attributes required to create a valid
  # RetentionPeriod. As you add validations to RetentionPeriod, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetentionPeriodsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all retention_periods as @retention_periods" do
      retention_period = RetentionPeriod.create! valid_attributes
      get :index, {}, valid_session
      assigns(:retention_periods).should eq([retention_period])
    end
  end

  describe "GET show" do
    it "assigns the requested retention_period as @retention_period" do
      retention_period = RetentionPeriod.create! valid_attributes
      get :show, {:id => retention_period.to_param}, valid_session
      assigns(:retention_period).should eq(retention_period)
    end
  end

  describe "GET new" do
    it "assigns a new retention_period as @retention_period" do
      get :new, {}, valid_session
      assigns(:retention_period).should be_a_new(RetentionPeriod)
    end
  end

  describe "GET edit" do
    it "assigns the requested retention_period as @retention_period" do
      retention_period = RetentionPeriod.create! valid_attributes
      get :edit, {:id => retention_period.to_param}, valid_session
      assigns(:retention_period).should eq(retention_period)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RetentionPeriod" do
        expect {
          post :create, {:retention_period => valid_attributes}, valid_session
        }.to change(RetentionPeriod, :count).by(1)
      end

      it "assigns a newly created retention_period as @retention_period" do
        post :create, {:retention_period => valid_attributes}, valid_session
        assigns(:retention_period).should be_a(RetentionPeriod)
        assigns(:retention_period).should be_persisted
      end

      it "redirects to the created retention_period" do
        post :create, {:retention_period => valid_attributes}, valid_session
        response.should redirect_to(RetentionPeriod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved retention_period as @retention_period" do
        # Trigger the behavior that occurs when invalid params are submitted
        RetentionPeriod.any_instance.stub(:save).and_return(false)
        post :create, {:retention_period => {}}, valid_session
        assigns(:retention_period).should be_a_new(RetentionPeriod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RetentionPeriod.any_instance.stub(:save).and_return(false)
        post :create, {:retention_period => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested retention_period" do
        retention_period = RetentionPeriod.create! valid_attributes
        # Assuming there are no other retention_periods in the database, this
        # specifies that the RetentionPeriod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RetentionPeriod.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => retention_period.to_param, :retention_period => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested retention_period as @retention_period" do
        retention_period = RetentionPeriod.create! valid_attributes
        put :update, {:id => retention_period.to_param, :retention_period => valid_attributes}, valid_session
        assigns(:retention_period).should eq(retention_period)
      end

      it "redirects to the retention_period" do
        retention_period = RetentionPeriod.create! valid_attributes
        put :update, {:id => retention_period.to_param, :retention_period => valid_attributes}, valid_session
        response.should redirect_to(retention_period)
      end
    end

    describe "with invalid params" do
      it "assigns the retention_period as @retention_period" do
        retention_period = RetentionPeriod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RetentionPeriod.any_instance.stub(:save).and_return(false)
        put :update, {:id => retention_period.to_param, :retention_period => {}}, valid_session
        assigns(:retention_period).should eq(retention_period)
      end

      it "re-renders the 'edit' template" do
        retention_period = RetentionPeriod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RetentionPeriod.any_instance.stub(:save).and_return(false)
        put :update, {:id => retention_period.to_param, :retention_period => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested retention_period" do
      retention_period = RetentionPeriod.create! valid_attributes
      expect {
        delete :destroy, {:id => retention_period.to_param}, valid_session
      }.to change(RetentionPeriod, :count).by(-1)
    end

    it "redirects to the retention_periods list" do
      retention_period = RetentionPeriod.create! valid_attributes
      delete :destroy, {:id => retention_period.to_param}, valid_session
      response.should redirect_to(retention_periods_url)
    end
  end

end
