require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SeriesHasManifestationsController do

  # This should return the minimal set of attributes required to create a valid
  # SeriesHasManifestation. As you add validations to SeriesHasManifestation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all series_has_manifestations as @series_has_manifestations" do
      series_has_manifestation = SeriesHasManifestation.create! valid_attributes
      get :index
      assigns(:series_has_manifestations).should eq([series_has_manifestation])
    end
  end

  describe "GET show" do
    it "assigns the requested series_has_manifestation as @series_has_manifestation" do
      series_has_manifestation = SeriesHasManifestation.create! valid_attributes
      get :show, :id => series_has_manifestation.id.to_s
      assigns(:series_has_manifestation).should eq(series_has_manifestation)
    end
  end

  describe "GET new" do
    it "assigns a new series_has_manifestation as @series_has_manifestation" do
      get :new
      assigns(:series_has_manifestation).should be_a_new(SeriesHasManifestation)
    end
  end

  describe "GET edit" do
    it "assigns the requested series_has_manifestation as @series_has_manifestation" do
      series_has_manifestation = SeriesHasManifestation.create! valid_attributes
      get :edit, :id => series_has_manifestation.id.to_s
      assigns(:series_has_manifestation).should eq(series_has_manifestation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SeriesHasManifestation" do
        expect {
          post :create, :series_has_manifestation => valid_attributes
        }.to change(SeriesHasManifestation, :count).by(1)
      end

      it "assigns a newly created series_has_manifestation as @series_has_manifestation" do
        post :create, :series_has_manifestation => valid_attributes
        assigns(:series_has_manifestation).should be_a(SeriesHasManifestation)
        assigns(:series_has_manifestation).should be_persisted
      end

      it "redirects to the created series_has_manifestation" do
        post :create, :series_has_manifestation => valid_attributes
        response.should redirect_to(SeriesHasManifestation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved series_has_manifestation as @series_has_manifestation" do
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesHasManifestation.any_instance.stub(:save).and_return(false)
        post :create, :series_has_manifestation => {}
        assigns(:series_has_manifestation).should be_a_new(SeriesHasManifestation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesHasManifestation.any_instance.stub(:save).and_return(false)
        post :create, :series_has_manifestation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested series_has_manifestation" do
        series_has_manifestation = SeriesHasManifestation.create! valid_attributes
        # Assuming there are no other series_has_manifestations in the database, this
        # specifies that the SeriesHasManifestation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SeriesHasManifestation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => series_has_manifestation.id, :series_has_manifestation => {'these' => 'params'}
      end

      it "assigns the requested series_has_manifestation as @series_has_manifestation" do
        series_has_manifestation = SeriesHasManifestation.create! valid_attributes
        put :update, :id => series_has_manifestation.id, :series_has_manifestation => valid_attributes
        assigns(:series_has_manifestation).should eq(series_has_manifestation)
      end

      it "redirects to the series_has_manifestation" do
        series_has_manifestation = SeriesHasManifestation.create! valid_attributes
        put :update, :id => series_has_manifestation.id, :series_has_manifestation => valid_attributes
        response.should redirect_to(series_has_manifestation)
      end
    end

    describe "with invalid params" do
      it "assigns the series_has_manifestation as @series_has_manifestation" do
        series_has_manifestation = SeriesHasManifestation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesHasManifestation.any_instance.stub(:save).and_return(false)
        put :update, :id => series_has_manifestation.id.to_s, :series_has_manifestation => {}
        assigns(:series_has_manifestation).should eq(series_has_manifestation)
      end

      it "re-renders the 'edit' template" do
        series_has_manifestation = SeriesHasManifestation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesHasManifestation.any_instance.stub(:save).and_return(false)
        put :update, :id => series_has_manifestation.id.to_s, :series_has_manifestation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested series_has_manifestation" do
      series_has_manifestation = SeriesHasManifestation.create! valid_attributes
      expect {
        delete :destroy, :id => series_has_manifestation.id.to_s
      }.to change(SeriesHasManifestation, :count).by(-1)
    end

    it "redirects to the series_has_manifestations list" do
      series_has_manifestation = SeriesHasManifestation.create! valid_attributes
      delete :destroy, :id => series_has_manifestation.id.to_s
      response.should redirect_to(series_has_manifestations_url)
    end
  end

end
