require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SeriesStatementRelationshipTypesController do

  # This should return the minimal set of attributes required to create a valid
  # SeriesStatementRelationshipType. As you add validations to SeriesStatementRelationshipType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "display_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SeriesStatementRelationshipTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all series_statement_relationship_types as @series_statement_relationship_types" do
      series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:series_statement_relationship_types).should eq([series_statement_relationship_type])
    end
  end

  describe "GET show" do
    it "assigns the requested series_statement_relationship_type as @series_statement_relationship_type" do
      series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
      get :show, {:id => series_statement_relationship_type.to_param}, valid_session
      assigns(:series_statement_relationship_type).should eq(series_statement_relationship_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested series_statement_relationship_type as @series_statement_relationship_type" do
      series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
      get :edit, {:id => series_statement_relationship_type.to_param}, valid_session
      assigns(:series_statement_relationship_type).should eq(series_statement_relationship_type)
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested series_statement_relationship_type" do
        series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
        # Assuming there are no other series_statement_relationship_types in the database, this
        # specifies that the SeriesStatementRelationshipType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SeriesStatementRelationshipType.any_instance.should_receive(:update_attributes).with({ "display_name" => "MyString" })
        put :update, {:id => series_statement_relationship_type.to_param, :series_statement_relationship_type => { "display_name" => "MyString" }}, valid_session
      end

      it "assigns the requested series_statement_relationship_type as @series_statement_relationship_type" do
        series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
        put :update, {:id => series_statement_relationship_type.to_param, :series_statement_relationship_type => valid_attributes}, valid_session
        assigns(:series_statement_relationship_type).should eq(series_statement_relationship_type)
      end

      it "redirects to the series_statement_relationship_type" do
        series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
        put :update, {:id => series_statement_relationship_type.to_param, :series_statement_relationship_type => valid_attributes}, valid_session
        response.should redirect_to(series_statement_relationship_type)
      end
    end

    describe "with invalid params" do
      it "assigns the series_statement_relationship_type as @series_statement_relationship_type" do
        series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesStatementRelationshipType.any_instance.stub(:save).and_return(false)
        put :update, {:id => series_statement_relationship_type.to_param, :series_statement_relationship_type => { "display_name" => "invalid value" }}, valid_session
        assigns(:series_statement_relationship_type).should eq(series_statement_relationship_type)
      end

      it "re-renders the 'edit' template" do
        series_statement_relationship_type = SeriesStatementRelationshipType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SeriesStatementRelationshipType.any_instance.stub(:save).and_return(false)
        put :update, {:id => series_statement_relationship_type.to_param, :series_statement_relationship_type => { "display_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end
end
