require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThemasController do

  # This should return the minimal set of attributes required to create a valid
  # Thema. As you add validations to Thema, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThemasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all themas as @themas" do
      thema = Thema.create! valid_attributes
      get :index, {}, valid_session
      assigns(:themas).should eq([thema])
    end
  end

  describe "GET show" do
    it "assigns the requested thema as @thema" do
      thema = Thema.create! valid_attributes
      get :show, {:id => thema.to_param}, valid_session
      assigns(:thema).should eq(thema)
    end
  end

  describe "GET new" do
    it "assigns a new thema as @thema" do
      get :new, {}, valid_session
      assigns(:thema).should be_a_new(Thema)
    end
  end

  describe "GET edit" do
    it "assigns the requested thema as @thema" do
      thema = Thema.create! valid_attributes
      get :edit, {:id => thema.to_param}, valid_session
      assigns(:thema).should eq(thema)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Thema" do
        expect {
          post :create, {:thema => valid_attributes}, valid_session
        }.to change(Thema, :count).by(1)
      end

      it "assigns a newly created thema as @thema" do
        post :create, {:thema => valid_attributes}, valid_session
        assigns(:thema).should be_a(Thema)
        assigns(:thema).should be_persisted
      end

      it "redirects to the created thema" do
        post :create, {:thema => valid_attributes}, valid_session
        response.should redirect_to(Thema.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thema as @thema" do
        # Trigger the behavior that occurs when invalid params are submitted
        Thema.any_instance.stub(:save).and_return(false)
        post :create, {:thema => { "name" => "invalid value" }}, valid_session
        assigns(:thema).should be_a_new(Thema)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Thema.any_instance.stub(:save).and_return(false)
        post :create, {:thema => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested thema" do
        thema = Thema.create! valid_attributes
        # Assuming there are no other themas in the database, this
        # specifies that the Thema created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Thema.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => thema.to_param, :thema => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested thema as @thema" do
        thema = Thema.create! valid_attributes
        put :update, {:id => thema.to_param, :thema => valid_attributes}, valid_session
        assigns(:thema).should eq(thema)
      end

      it "redirects to the thema" do
        thema = Thema.create! valid_attributes
        put :update, {:id => thema.to_param, :thema => valid_attributes}, valid_session
        response.should redirect_to(thema)
      end
    end

    describe "with invalid params" do
      it "assigns the thema as @thema" do
        thema = Thema.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Thema.any_instance.stub(:save).and_return(false)
        put :update, {:id => thema.to_param, :thema => { "name" => "invalid value" }}, valid_session
        assigns(:thema).should eq(thema)
      end

      it "re-renders the 'edit' template" do
        thema = Thema.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Thema.any_instance.stub(:save).and_return(false)
        put :update, {:id => thema.to_param, :thema => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thema" do
      thema = Thema.create! valid_attributes
      expect {
        delete :destroy, {:id => thema.to_param}, valid_session
      }.to change(Thema, :count).by(-1)
    end

    it "redirects to the themas list" do
      thema = Thema.create! valid_attributes
      delete :destroy, {:id => thema.to_param}, valid_session
      response.should redirect_to(themas_url)
    end
  end

end
